name: Setup CUDA

inputs:
  version:
    description: "CUDA version"
    required: true
    default: "12.9.1.576"
    type: string

outputs:
  cuda-path:
    description: "CUDA path"

runs:
  using: "composite"
  steps:
    - name: Install CUDA (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      env:
        VERSION: ${{ inputs.version }}
      run: |
        $version = $env:VERSION.Split('.')[0..1] -join '.'
        $version_slug = $version.Replace('.', '_')
        $cuda_path = "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v${version}"
        choco install cuda --version=${{ inputs.version }} -y
        Add-Content -Path $env:GITHUB_ENV -Value "CUDA_PATH=${cuda_path}"
        Add-Content -Path $env:GITHUB_ENV -Value "CUDA_PATH_V${version_slug}=${cuda_path}"
        Add-Content -Path $env:GITHUB_PATH -Value "${cuda_path}\bin"
        Add-Content -Path $env:GITHUB_PATH -Value "${cuda_path}\libnvvp"
        Add-Content -Path $env:GITHUB_OUTPUT -Value "cuda-path=${cuda_path}"
