SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_SYSTEM_PROCESSOR aarch64)

set(ARCH_PREFIX aarch64-w64-mingw32)

SET(CMAKE_C_COMPILER ${ARCH_PREFIX}-clang)
SET(CMAKE_CXX_COMPILER ${ARCH_PREFIX}-clang++)
SET(CMAKE_RC_COMPILER ${ARCH_PREFIX}-windres)

set(CLANG ON)
set(MINGW ON)
