SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR aarch64)

set(ARCH_PREFIX aarch64-linux-gnu)

SET(CMAKE_C_COMPILER ${ARCH_PREFIX}-gcc)
SET(CMAKE_CXX_COMPILER ${ARCH_PREFIX}-g++)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(CROSS_COMPILE TRUE)
