if(WIN32)
SET(PATH_EXE .exe)
endif()
SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER_TARGET aarch64-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET aarch64-windows-msvc)

SET(CMAKE_C_COMPILER clang)
SET(CMAKE_CXX_COMPILER clang++)
SET(CMAKE_RC_COMPILER windres)

set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT} -target ${CMAKE_C_COMPILER_TARGET}")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT} -target ${CMAKE_CXX_COMPILER_TARGET}")

set(CLANG ON)
