if(WIN32)
SET(PATH_EXE .exe)
endif()
SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)

set(ARCH_PREFIX x86_64-w64-mingw32)

SET(CMAKE_C_COMPILER ${ARCH_PREFIX}-clang${PATH_EXE})
SET(CMAKE_CXX_COMPILER ${ARCH_PREFIX}-clang++${PATH_EXE})
SET(CMAKE_RC_COMPILER ${ARCH_PREFIX}-windres${PATH_EXE})
set(CMAKE_EXE_LINKER_FLAGS "-Wl,-pdb= -fopenmp")
set(CMAKE_SHARED_LINKER_FLAGS "-Wl,-pdb= -fopenmp")

set(CLANG ON)
