SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_SYSTEM_PROCESSOR x86_64)

set(ARCH_PREFIX x86_64-w64-mingw32)

SET(CMAKE_C_COMPILER ${ARCH_PREFIX}-clang)
SET(CMAKE_CXX_COMPILER ${ARCH_PREFIX}-clang++)
SET(CMAKE_RC_COMPILER ${ARCH_PREFIX}-windres)

set(CLANG ON)
