name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        lfs: 'true'
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: node_modules cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
    - name: gguf models cache
      uses: actions/cache@v4
      with:
        path: test/*.gguf
        key: ${{ runner.os }}-gguf-models-${{ hashFiles('test/*.gguf') }}
    - run: yarn install
    - run: yarn build-native && rm -rf build
    - run: yarn test
