name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install LLVM and Clang
      run: |
        curl -L https://apt.llvm.org/llvm.sh | ALL=1 sudo bash -s 18
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
        sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-18 100
        sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-18 100
        sudo update-alternatives --install /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-18 100
        sudo update-alternatives --install /usr/bin/llvm-nm llvm-nm /usr/bin/llvm-nm-18 100
    - name: gguf models cache
      uses: actions/cache@v4
      with:
        path: test/*.gguf
        key: ${{ runner.os }}-gguf-models-${{ hashFiles('test/*.gguf') }}
    - run: npm run prebuild-native && npm install --omit=optional --build-from-source
    - run: npm run test
