name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: node_modules cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: '18'
        platform: x64
    - name: gguf models cache
      uses: actions/cache@v4
      with:
        path: test/*.gguf
        key: ${{ runner.os }}-gguf-models-${{ hashFiles('test/*.gguf') }}
    - run: npm ci
    - run: npm run test
